CMAKE_MINIMUM_REQUIRED( VERSION 2.8 )

IF( WIN32 )
	SET( FLTK_PATCH )
ELSE()
	SET( FLTK_PATCH PATCH_COMMAND patch -p1 < ${CMAKE_SOURCE_DIR}/fltk_1.3.3_static_cast-CGFloat.patch )
ENDIF()

ExternalProject_Add( FLTK
	${FLTK_PATCH}
	URL ${CMAKE_SOURCE_DIR}/fltk-1.3.3-source.tar.gz
	CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
		-DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
		-DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
		-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
		-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
		-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
		-DOPTION_BUILD_EXAMPLES:BOOL=OFF
		-DOPTION_USE_SYSTEM_LIBJPEG:BOOL=OFF
		-DOPTION_USE_SYSTEM_ZLIB:BOOL=OFF
		-DOPTION_USE_SYSTEM_LIBPNG:BOOL=OFF
	
)
ExternalProject_Get_Property( FLTK INSTALL_DIR )
SET( FLTK_INSTALL_DIR ${INSTALL_DIR} )
